---
- hosts: all
  tasks:
  - name: Check if Docker Compose is installedi
    command: docker-compose --version
    register: docker_compose_check
    ignore_errors: yes

  - name: Download and install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1
